name: Changelog & release

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  create-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Changelog
        uses: vlachdev/workflows/changelog@v3
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
